# Friendly name for the workflow in GitHub
name: Continuous Integration (CI)

# Run the workflow each time code is pushed, or when a pull-request is created
on: [push, pull_request]

jobs:
  # Build the app
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Node packages
        run: npm install
      - name: Start Application
        run: npm start &  # Ensure the app is running in the background

  # Run security scans
  scan:
    name: Run security scans
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Run the OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'http://localhost:3000/#' 

      # Publish the scan results as an artifact
      - uses: actions/upload-artifact@v3
        with: 
          name: zap-report
          path: zap_report.html

  # Deploy the app
  deploy:
    name: Deploy
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy the app..."
      - run: echo "Not implemented to save time when running the workflow"